/*
 * This source file was generated by the Gradle 'init' task
 */
package org.nosotros;
import org.glassfish.tyrus.server.Server;

public class App {

    public static boolean debug = true;
    public static void main(String[] args) {

        HTTPServer httpServer = new HTTPServer();
        Thread httpThread = new Thread(httpServer);
        httpThread.start();

        Server server = new Server("localhost", 8080, "/websockets", null, WebServer.class);
        try {
            server.start();
            System.out.println("Presiona cualquier tecla para detener el servidor..");
            System.in.read();
        } catch (Exception e) {
            throw new RuntimeException(e);
        } finally {
            server.stop();
        }
    }
}
